### ISSUE TITLE
Biggest asks

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-web-client#121]
Listing here the current biggest asks from users:
* [ ] #117 ctrl+w closing the window is confusing for 50% of new users
* [ ] #28 mouse sensitivity is a recurrent ask
* [ ] #59 breaking animation being absent is confusing many users: seems like digging doesn't work
* [ ] #10 inventory implementation seems needed

**Comment by ShrimpyStuff** [comment]
The first thing to solve we just need to add a warning because there's no other way
